language: cpp

os: linux
dist: xenial

services:
  - docker

# env:
#   global:
#     - DEVKITPRO=/opt/devkitpro    
#     - DEVKITARM=/opt/devkitpro/devkitARM
    
# cache:
#   directories:
#     - "$HOME/.local"
#     - "$DEVKITPRO"

# install:
#   - sudo dpkg -i pacman.deb
#   - sudo dkp-pacman -Sy
#   - sudo dkp-pacman -S devkitARM general-tools dstools ndstool libnds libfat-nds grit mmutil --noconfirm
#   - git clone https://github.com/RocketRobz/libnds.git
#   - cd libnds/
#   - sudo make install
#   - cd ..
#   - sudo rm -r libnds/
#   - 
#   - git clone https://github.com/RocketRobz/libnds.git
#   - cd libnds/
#   - sudo make install
#   - cd ..
#   - sudo rm -r libnds/
#   - 
#   - export DEVKITPRO=/opt/devkitpro
#   - export DEVKITARM=${DEVKITPRO}/devkitARM


# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-4.9
#     - g++-4.9
#     - libstdc++6
#     - lftp

before_install:
  - docker build -t twilightmenu --label twilightmenu ./docker
  - docker ps -a
  - sudo apt-get install -y p7zip-full


script:
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  # - 7z x libnds.7z
  # - sudo cp -r libnds/* /opt/devkitpro/libnds/
  # - make package
  - chmod +x ./compile_docker.sh
  - ./compile_docker.sh
  - cd booter/
  - chmod +x make_cia
  - ./make_cia --srl="booter.nds"
  - mkdir -p "../7zfile/3DS - CFW users/"
  - cp "booter.cia" "../7zfile/3DS - CFW users/TWiLight Menu.cia"
  - cd ../rungame/
  - chmod +x make_cia
  - ./make_cia --srl="rungame.nds"
  - cp "rungame.cia" "../7zfile/3DS - CFW users/TWiLight Menu - Game booter.cia"
  - cd ../
  - mv 7zfile/ TWiLightMenu/
  - 7z a TWiLightMenu.7z TWiLightMenu/
  
after_success:
  - curl -o send.sh https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - curl -o send.sh https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

before_deploy:
  - git config --local user.name "TWLBot"
  - git clone https://$GITHUB_TOKEN@github.com/TWLBot/Builds.git
  - cd Builds/
  - cp ../TWiLightMenu.7z TWiLightMenu.7z
  - git stage .
  - git commit -m "TWiLightMenu | $COMMIT_TAG"
  - git push origin master
  - export CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')
  - git tag v$CURRENT_DATE

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file: TWiLightMenu.7z
  skip_cleanup: true
  repo: TWLBot/Builds
  prerelease: true
  name: TWiLightMenu | $COMMIT_TAG
  body: $COMMIT_MESSAGE
