blank_issues_enabled: false
contact_links:
  - name: Support (thru TWL Mode Hacking Discord Server)
    url: https://discord.gg/yD3spjv
    about: "Please use the #support Discord Server to ask for support-related questions, such as needing assistance to launch TWiLight Menu++"
  - name: DS game issue
    url: https://github.com/ahezard/nds-bootstrap/issues/new
    about: Please use the nds-bootstrap Github Repository to report issues related to running Nintendo DS applications as `.nds` files (not as a retail cart) via B4DS/nds-bootstrap (and not via Unlaunch)
  - name: GBA game issue
    url: https://github.com/Gericom/GBARunner2/issues/new
    about: Please use the GBARunner2 Github Repository to report issues related to running GameBoy Advance applications as `.gba` files (not as Slot-2 for DS Phat/Lite consoles), or the GBARunner2 GUI
  - name: MPEG4 issue
    url: https://github.com/Gericom/YouTubeDS/issues/new
    about: Please use the MPEG4Player/YouTubeDS Github Repository to report issues related to .mp4 playback
